[custom]
;个人专属规则集

;规则集定义
ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,[]GEOIP,private,no-resolve
ruleset=DIRECT,[]GEOIP,LAN,no-resolve
ruleset=🇭🇰 mytvsuperAD,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/mytvsuperAD.list
ruleset=🇭🇰 myTVSUPER,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/myTVSUPER.list
ruleset=🇭🇰 ViuTV,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/ViuTV.list
ruleset=🇭🇰 NowTV,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/NowTV.list
ruleset=🇭🇰 RTHK,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/RTHK.list
ruleset=🇭🇰 HOY,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/HOY.list
ruleset=📺 YouTube,[]GEOSITE,youtube
ruleset=📢 Google Services,[]GEOSITE,google
ruleset=📢 Google Services,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/TimeAndroid.list
ruleset=📢 Google Services,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 Google Services,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 Google Services,https://whatshub.top/rule/Google.list
ruleset=📢 Google Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 Google Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 Google Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🇺🇲 OpenAI,[]GEOSITE,openai
ruleset=🇺🇲 OpenAI,https://whatshub.top/rule/OpenAI.list
ruleset=🇺🇲 ChatGPT,https://whatshub.top/rule/ChatGPT.list
ruleset=🎵 TikTok,[]GEOSITE,tiktok
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🍃 Microsoft Services,[]GEOSITE,microsoft
ruleset=🍃 Microsoft Services,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Ⓜ️ Bing,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/Bing.list
ruleset=🇨🇳 TaiWan,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/TaiWan.list
ruleset=🇺🇲 USA,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/USA.list
ruleset=🇸🇬 Singapore,https://raw.githubusercontent.com/ErrrHK/Global-Streaming-Ruleset/refs/heads/main/Singapore.list
ruleset=DIRECT,[]DOMAIN-SUFFIX,time.windows.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,client.wns.windows.com
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOSITE,cn
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 Proxies,[]FINAL

; 策略組
custom_proxy_group=🚀 Proxies`select`[]♻️ Auto - UrlTest`[]🇭🇰 myTVSUPER`[]🇭🇰 mytvsuperAD`[]🇭🇰 ViuTV`[]🇭🇰 NowTV`[]🇭🇰 RTHK`[]🇭🇰 HOY`[]🇨🇳 TaiWan`[]🇺🇲 USA`[]🇸🇬 Singapore`[]DIRECT`.*
custom_proxy_group=♻️ Auto - UrlTest`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 myTVSUPER`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)
custom_proxy_group=🇭🇰 mytvsuperAD`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)`[]DIRECT`[]REJECT
custom_proxy_group=🇭🇰 ViuTV`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)
custom_proxy_group=🇭🇰 NowTV`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)
custom_proxy_group=🇭🇰 RTHK`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)
custom_proxy_group=🇭🇰 HOY`select`(?i)(🇭🇰|香港|HK|Hong Kong|HongKong)
custom_proxy_group=🇨🇳 TaiWan`select`(?i)(🇹🇼|台湾|台灣|TW|Taiwan|Taipei)
custom_proxy_group=🇺🇲 USA`select`(?i)(🇺🇸|美国|美國|US|United States|Los Angeles|San Jose|Seattle|New York|Portland|Dallas|Oregon|Phoenix|Fremont|Silicon Valley|Las Vegas|Santa Clara|Chicago)
custom_proxy_group=🇸🇬 Singapore`select`(?i)(🇸🇬|新加坡|SG|Singapore|狮城|獅城)
custom_proxy_group=📢 Google Services`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=📺 YouTube`select`[]🚀 Proxies`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=🍃 Microsoft Services`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=🇺🇲 OpenAI`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=🇺🇲 ChatGPT`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=🎵 TikTok`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*
custom_proxy_group=Ⓜ️ Bing`select`[]🚀 Proxies`select`[]♻️ Auto - UrlTest`[]DIRECT`.*

; 啟用自訂規則
enable_rule_generator=true
overwrite_original_rules=true
